services:
  totpguard_api:
    build:
      context: .
      dockerfile: TOTPGuard.Api/Dockerfile
    container_name: totpguard_api
    networks:
      - totpguard_net
    expose:
      - "8080"

  totpguard_client:
    build:
      context: TOTPGuard.Client
      dockerfile: TOTPGuard.Client/Dockerfile
    container_name: totpguard_client
    depends_on:
      - totpguard_api
    networks:
      - totpguard_net
    ports:
      - "80:80"

networks:
  totpguard_net:
    driver: bridge
